export const FIND_HOSPITALS = 'FIND_HOSPITALS'
export const FIND_HOSPITAL = 'FIND_HOSPITAL'

export const FIND_HOSPITAL_MAIN = 'FIND_HOSPITAL_MAIN'
export const FINDT = 'FINDT'

export const FIND_CERTIFICATELIST = 'FIND_CERTIFICATELIST'
export const FIND_CERTIFICATECONTENT = 'FIND_CERTIFICATECONTENT'

export const FIND_DEP = 'FIND_DEP'
